using System.Collections;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using Unity.Netcode;
using Unity.Netcode.Transports.UTP;

/// <summary>
/// SOLID — SRP: Computes and renders real-time client performance metrics
/// (FPS and NGO Round-Trip Ping/RTT).
/// 
/// Can be:
/// 1. Automatically generated by GameSettingsManager when "Performance & Ping Overlay" is enabled.
/// 2. Manually attached to any TextMeshProUGUI element in a scene canvas if custom placement is desired.
/// </summary>
public class PerformanceOverlay : MonoBehaviour
{
    public static PerformanceOverlay Instance { get; private set; }

    [Header("Manual Binding (Optional)")]
    [Tooltip("Assign an existing TextMeshProUGUI component in your scene/canvas. If unassigned, a sleek corner overlay is generated automatically.")]
    public TextMeshProUGUI customText;

    [Header("Display Settings")]
    [Range(0.05f, 0.5f)]
    public float updateInterval = 0.18f;

    private TextMeshProUGUI _displayTMP;
    private CanvasGroup _canvasGroup;
    private float _smoothFps = 60f;
    private float _timer;

    // Palette
    private const string COLOR_GREEN  = "#2ECC71";
    private const string COLOR_YELLOW = "#F1C40F";
    private const string COLOR_RED    = "#E74C3C";
    private const string COLOR_MUTED  = "#667788";

    // =========================================================================
    //  Global Activation / Factory
    // =========================================================================
    public static void SetOverlayActive(bool active)
    {
        if (active)
        {
            EnsureInstance();
            if (Instance != null)
            {
                Instance.gameObject.SetActive(true);
            }
        }
        else
        {
            if (Instance != null)
            {
                Instance.gameObject.SetActive(false);
            }
        }
    }

    public static PerformanceOverlay EnsureInstance()
    {
        if (Instance != null) return Instance;

        // Check if an instance already exists in the scene
        var existing = FindFirstObjectByType<PerformanceOverlay>();
        if (existing != null)
        {
            Instance = existing;
            return Instance;
        }

        // Auto-generate persistent HUD overlay
        GameObject rootObj = new GameObject("[PerformanceOverlay_HUD]");
        DontDestroyOnLoad(rootObj);

        var overlay = rootObj.AddComponent<PerformanceOverlay>();
        overlay.BuildAutoHUD(rootObj);
        Instance = overlay;
        return Instance;
    }

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
            if (transform.parent == null)
            {
                DontDestroyOnLoad(gameObject);
            }
        }
        else if (Instance != this)
        {
            // If another instance already exists, respect the existing one
            Destroy(gameObject);
            return;
        }

        if (customText != null)
        {
            _displayTMP = customText;
        }
        else if (_displayTMP == null)
        {
            BuildAutoHUD(gameObject);
        }
    }

    private void Start()
    {
        // Align with GameSettingsManager state on startup
        if (GameSettingsManager.Instance != null)
        {
            gameObject.SetActive(GameSettingsManager.Instance.showPerformanceOverlay);
        }
    }

    private void OnEnable()
    {
        _smoothFps = 1f / Mathf.Max(0.0001f, Time.unscaledDeltaTime);
        _timer = 0f;
        UpdateMetricsDisplay();
    }

    private void Update()
    {
        float dt = Time.unscaledDeltaTime;
        if (dt > 0.0001f)
        {
            float currentFps = 1f / dt;
            _smoothFps = Mathf.Lerp(_smoothFps, currentFps, dt * 8.5f);
        }

        _timer += dt;
        if (_timer >= updateInterval)
        {
            _timer = 0f;
            UpdateMetricsDisplay();
        }
    }

    // =========================================================================
    //  Metrics Calculation & Rendering
    // =========================================================================
    private void UpdateMetricsDisplay()
    {
        if (_displayTMP == null) return;

        // 1. Calculate FPS string & color
        int fpsInt = Mathf.Clamp(Mathf.RoundToInt(_smoothFps), 1, 999);
        string fpsColor = (fpsInt >= 55) ? COLOR_GREEN : ((fpsInt >= 30) ? COLOR_YELLOW : COLOR_RED);

        // 2. Query NGO Ping / RTT
        string pingStr = "--";
        string pingColor = COLOR_MUTED;

        if (NetworkManager.Singleton != null && NetworkManager.Singleton.IsConnectedClient)
        {
            if (NetworkManager.Singleton.IsServer && NetworkManager.Singleton.IsClient)
            {
                // Local Host has zero network latency
                pingStr = "0 ms (Host)";
                pingColor = COLOR_GREEN;
            }
            else
            {
                ulong rtt = 0;
                var transport = NetworkManager.Singleton.NetworkConfig?.NetworkTransport;
                if (transport != null)
                {
                    rtt = transport.GetCurrentRtt(NetworkManager.ServerClientId);
                }

                pingStr = $"{rtt} ms";
                if (rtt <= 60)
                    pingColor = COLOR_GREEN;
                else if (rtt <= 110)
                    pingColor = COLOR_YELLOW;
                else
                    pingColor = COLOR_RED;
            }
        }
        else
        {
            pingStr = "Local";
            pingColor = COLOR_MUTED;
        }

        // Render sleek formatted string
        _displayTMP.text = $"FPS: <color={fpsColor}>{fpsInt}</color>   <color={COLOR_MUTED}>|</color>   PING: <color={pingColor}>{pingStr}</color>";
    }

    // =========================================================================
    //  Automatic HUD Canvas Construction
    // =========================================================================
    private void BuildAutoHUD(GameObject target)
    {
        // Add Canvas
        Canvas canvas = target.GetComponent<Canvas>();
        if (canvas == null) canvas = target.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.overrideSorting = true;
        canvas.sortingOrder = 9999; // Always render atop all game elements

        // Add CanvasScaler
        CanvasScaler scaler = target.GetComponent<CanvasScaler>();
        if (scaler == null) scaler = target.AddComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1080);
        scaler.matchWidthOrHeight = 0.5f;

        // Pill Container
        GameObject pill = new GameObject("PerfPill");
        pill.transform.SetParent(target.transform, false);

        RectTransform pillRect = pill.AddComponent<RectTransform>();
        pillRect.anchorMin = new Vector2(1f, 1f);
        pillRect.anchorMax = new Vector2(1f, 1f);
        pillRect.pivot     = new Vector2(1f, 1f);
        pillRect.anchoredPosition = new Vector2(-22f, -18f); // Top right margin
        pillRect.sizeDelta = new Vector2(245f, 32f);

        Image pillBg = pill.AddComponent<Image>();
        pillBg.color = new Color(0.04f, 0.06f, 0.09f, 0.78f); // Dark translucent gunmetal
        pillBg.raycastTarget = false;

        // Add sleek subtle outline
        Outline outline = pill.AddComponent<Outline>();
        outline.effectColor = new Color(0.18f, 0.22f, 0.28f, 0.65f);
        outline.effectDistance = new Vector2(1f, -1f);

        // Text Component
        GameObject textObj = new GameObject("MetricsText");
        textObj.transform.SetParent(pill.transform, false);

        RectTransform textRect = textObj.AddComponent<RectTransform>();
        textRect.anchorMin = Vector2.zero;
        textRect.anchorMax = Vector2.one;
        textRect.sizeDelta = Vector2.zero;
        textRect.anchoredPosition = Vector2.zero;

        TextMeshProUGUI tmp = textObj.AddComponent<TextMeshProUGUI>();
        tmp.fontSize = 13.5f;
        tmp.fontStyle = FontStyles.Bold;
        tmp.alignment = TextAlignmentOptions.Center;
        tmp.color = Color.white;
        tmp.raycastTarget = false;
        tmp.text = "FPS: <color=#2ECC71>--</color>   <color=#667788>|</color>   PING: <color=#667788>--</color>";

        _displayTMP = tmp;
    }
}
